#!/bin/bash

cd /home/bart_simp/Android/Sdk/

rm -r platform-tools

wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip

unzip \platform-tools-latest-linux.zip

rm platform-tools-latest-linux.zip

sudo cp platform-tools/adb /usr/bin/adb

sudo cp platform-tools/fastboot /usr/bin/fastboot
