#! /bin/bash

sudo mount /dev/sda5 /mnt

sudo mount --bind /dev /mnt/dev && \
sudo mount --bind /dev/pts /mnt/dev/pts && \
sudo mount --bind /proc /mnt/proc && \
sudo mount --bind /sys /mnt/sys

sudo chroot /mnt

grub-install /dev/sda && grub-install --recheck /dev/sda && update-grub

exit && sudo umount /mnt/dev && sudo umount /mnt/proc && sudo umount /mnt

