#!/bin/bash

##/local/bin/quick-system-info-mx
##wrapper script for inxi to do quick "inxi -F" and copy report to clipboard
##part of mx-goodies package

#requires xsel package

##locale stuff

TEXTDOMAINDIR=/usr/share/locale/ 
export TEXTDOMAIN="mx-goodies"

#setup

main(){

    #check for existing of inxi

    command -v inxi  >/dev/null  2>/dev/null || quit_error $"Required inxi app not found"

    run_report

    quit

}

run_report(){

    bash -c '( echo "[ code ]"; inxi -Fxrz  -c0 ; echo "[ /code ]" 2>/dev/null ) | xsel -ib 2>/dev/null &'
    echo
    bash -c 'inxi -Fxrz 2>/dev/null'
    echo
    echo $"Report copied to system clipboard"

}

quit(){
    echo
    read -n 1 -s -r -p $"Press any key to close"
    exit 0
}

quit_error(){
    local msg
    msg=$1
    echo "$msg"
    exit 1
}

main "$@"
